# SPDX-FileCopyrightText: 2026-present Biosimulant Team
#
# SPDX-License-Identifier: MIT
"""Extension contracts for product-only Biosimulant CLI behavior."""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Protocol, Sequence


DEFAULT_PRODUCT_EXTENSION = "biosimulant-product"
DEFAULT_INSTALL_HINT = (
    "Install or configure the Biosimulant Desktop/product CLI extension, then retry this command."
)


class CliExtension(Protocol):
    """Product extension capable of handling a CLI command path."""

    def run_cli_command(self, command: str, argv: Sequence[str], *, prog: str) -> int | None:
        """Run an extension-owned command and return a process-style exit code."""


class AuthProvider(Protocol):
    """Extension interface for Hub auth and secure credential storage."""

    def run_auth_command(self, argv: Sequence[str], *, prog: str) -> int | None:
        """Run an auth command such as login, status, or logout."""


class HubProvider(Protocol):
    """Extension interface for Biosimulant Hub API commands."""

    def run_hub_command(self, argv: Sequence[str], *, prog: str) -> int | None:
        """Run a Hub command such as listing, publishing, or downloading labs."""


class CloudRunProvider(Protocol):
    """Extension interface for hosted run and cloud job commands."""

    def run_cloud_command(self, argv: Sequence[str], *, prog: str) -> int | None:
        """Run a cloud-backed command."""


class DesktopStateProvider(Protocol):
    """Extension interface for Desktop-managed state and indexes."""

    def run_desktop_state_command(self, argv: Sequence[str], *, prog: str) -> int | None:
        """Run a command that needs Desktop state, indexes, or secure storage."""


class ManagedRuntimeProvider(Protocol):
    """Extension interface for managed runtime bootstrap and inspection."""

    def run_runtime_command(self, argv: Sequence[str], *, prog: str) -> int | None:
        """Run a Desktop/product managed-runtime command."""


@dataclass(frozen=True)
class ExtensionCommandSpec:
    """Machine-readable ownership metadata for extension-only CLI commands."""

    command: str
    category: str
    summary: str
    extension: str = DEFAULT_PRODUCT_EXTENSION
    install_hint: str = DEFAULT_INSTALL_HINT


class ExtensionUnavailableError(RuntimeError):
    """Raised when an extension-owned command is invoked without the extension."""

    def __init__(
        self,
        spec: ExtensionCommandSpec,
        argv: Sequence[str] = (),
        *,
        prog: str = "biosimulant",
    ) -> None:
        self.spec = spec
        self.argv = tuple(str(item) for item in argv)
        self.prog = prog
        super().__init__(
            f"{spec.command} requires the {spec.extension} extension: {spec.summary}"
        )

    @property
    def invocation(self) -> str:
        return " ".join([self.prog, *self.argv]).strip()


_PRODUCT_COMMANDS: tuple[ExtensionCommandSpec, ...] = (
    ExtensionCommandSpec("auth", "auth", "Hub login, logout, token exchange, and secure credentials."),
    ExtensionCommandSpec("config", "desktop", "Product configuration backed by Desktop state."),
    ExtensionCommandSpec("commands", "desktop", "Product command catalog generated by the Desktop CLI."),
    ExtensionCommandSpec("doctor", "desktop", "Desktop/product installation diagnostics."),
    ExtensionCommandSpec("which", "desktop", "Desktop/product CLI path discovery."),
    ExtensionCommandSpec("install-cli", "desktop", "Desktop-managed CLI installation."),
    ExtensionCommandSpec("uninstall-cli", "desktop", "Desktop-managed CLI removal."),
    ExtensionCommandSpec("raw", "desktop", "Raw Desktop runtime command passthrough."),
    ExtensionCommandSpec("models", "desktop/hub", "Desktop model registry and Hub-backed model workflows."),
    ExtensionCommandSpec("runs", "desktop/cloud", "Desktop run index, cloud runs, upload, logs, and reports."),
    ExtensionCommandSpec("hub", "hub/cloud", "Hub labs, Hub runs, publishing, downloads, and cloud APIs."),
    ExtensionCommandSpec("runtime", "desktop", "Desktop-managed Python/runtime bootstrap and status."),
    ExtensionCommandSpec("settings", "desktop", "Desktop settings, logs, data directory, and dashboard integration."),
    ExtensionCommandSpec("jobs", "cloud", "Commercial hosted jobs and job inspection."),
    ExtensionCommandSpec("self", "desktop", "Product CLI self-update behavior."),
    ExtensionCommandSpec("agent", "agent/hub", "Authenticated product agent workflow."),
    ExtensionCommandSpec("agents", "agent/hub", "Authenticated product agent workflows."),
    ExtensionCommandSpec("chat", "agent/hub", "Authenticated product chat workflow."),
    ExtensionCommandSpec("labs list", "desktop/hub", "Desktop lab index and Hub-aware lab listing."),
    ExtensionCommandSpec("labs get", "desktop/hub", "Desktop lab index lookup."),
    ExtensionCommandSpec("labs create", "desktop", "Desktop lab registry creation."),
    ExtensionCommandSpec("labs import", "desktop", "Desktop lab import and registry indexing."),
    ExtensionCommandSpec("labs pull", "hub", "Hub lab download and dependency sync."),
    ExtensionCommandSpec("labs save", "desktop", "Desktop lab state persistence."),
    ExtensionCommandSpec("labs rename", "desktop", "Desktop lab registry mutation."),
    ExtensionCommandSpec("labs delete", "desktop", "Desktop lab registry deletion."),
    ExtensionCommandSpec("labs open", "desktop", "Desktop window and local project opening."),
    ExtensionCommandSpec("labs vendor-model", "desktop", "Desktop-owned lab model vendoring."),
    ExtensionCommandSpec("labs change-model", "desktop", "Desktop-owned lab model replacement."),
    ExtensionCommandSpec("labs inspect-owned", "desktop", "Desktop ownership metadata inspection."),
    ExtensionCommandSpec("labs add-model", "desktop", "Desktop-aware model addition to a lab."),
    ExtensionCommandSpec("labs export", "desktop", "Desktop-managed lab export."),
    ExtensionCommandSpec("labs publish", "hub", "Hub lab publishing and visibility management."),
    ExtensionCommandSpec("packages preview", "desktop", "Desktop package preview."),
    ExtensionCommandSpec("packages import", "desktop", "Desktop package import."),
    ExtensionCommandSpec("packages export-model", "desktop", "Desktop model package export."),
    ExtensionCommandSpec("packages export-lab", "desktop", "Desktop lab package export."),
    ExtensionCommandSpec("packages publish", "hub", "Package publishing to Biosimulant Hub."),
    ExtensionCommandSpec("packages ci", "hub", "CI publish orchestration for package repositories."),
)

_PRODUCT_COMMAND_MAP: dict[str, ExtensionCommandSpec] = {
    spec.command: spec for spec in _PRODUCT_COMMANDS
}
_EXTENSIONS: dict[str, CliExtension] = {}


def extension_command_specs() -> tuple[ExtensionCommandSpec, ...]:
    """Return known product-extension command ownership metadata."""

    return _PRODUCT_COMMANDS


def get_extension_command_spec(command: str) -> ExtensionCommandSpec | None:
    """Return ownership metadata for an extension-only command path."""

    return _PRODUCT_COMMAND_MAP.get(command)


def is_extension_command_path(command: str) -> bool:
    """Return true when a command path is owned by an extension."""

    return command in _PRODUCT_COMMAND_MAP


def register_extension(name: str, extension: CliExtension) -> None:
    """Register an extension implementation for CLI delegation."""

    if not name.strip():
        raise ValueError("Extension name is required")
    _EXTENSIONS[name] = extension


def unregister_extension(name: str) -> None:
    """Remove a registered extension if present."""

    _EXTENSIONS.pop(name, None)


def clear_extensions() -> None:
    """Clear registered extensions. Intended for tests and controlled bootstrap."""

    _EXTENSIONS.clear()


def get_extension(name: str) -> CliExtension | None:
    """Return a registered extension by name."""

    return _EXTENSIONS.get(name)


def run_extension_command(command: str, argv: Sequence[str], *, prog: str) -> int:
    """Delegate an extension-owned command or raise a clean unavailable error."""

    spec = get_extension_command_spec(command)
    if spec is None:
        raise ValueError(f"Unknown extension command: {command}")

    extension = get_extension(spec.extension)
    if extension is None:
        raise ExtensionUnavailableError(spec, argv, prog=prog)

    result = extension.run_cli_command(command, list(argv), prog=prog)
    return int(result or 0)


def extension_error_payload(error: ExtensionUnavailableError) -> dict[str, Any]:
    """Return machine-readable missing-extension error details."""

    spec = error.spec
    return {
        "error": "extension_unavailable",
        "command": spec.command,
        "invocation": error.invocation,
        "category": spec.category,
        "extension": spec.extension,
        "summary": spec.summary,
        "install_hint": spec.install_hint,
    }
